// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA52FkZfauDn_Vd0TlX3nNsjymKgvA4ucw',
    appId: '1:107700877622:android:642e477f5264e3a05fdb97',
    messagingSenderId: '107700877622',
    projectId: 'ne-nerede-d82a9',
    storageBucket: 'ne-nerede-d82a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsYHxPPmryQBNo0MwmhICUeBgpMaAxSBE',
    appId: '1:107700877622:ios:7e5230ba90ba4b525fdb97',
    messagingSenderId: '107700877622',
    projectId: 'ne-nerede-d82a9',
    storageBucket: 'ne-nerede-d82a9.appspot.com',
    androidClientId: '107700877622-tlr7rhrqcs9270rnsfkjqhp0qnnsiktv.apps.googleusercontent.com',
    iosClientId: '107700877622-oiencl7qe1jnqtugndv6pjifmkko9rgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.neNerede',
  );
}
